version: '3.8'

services:
  db:
    container_name: postgrechallenge
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: azerty123
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: challenge@test.com
      PGADMIN_DEFAULT_PASSWORD: azerty789
    ports:
      - "5050:80"